# Spring Profiles
spring.profiles.active=dev

# Default values (used if no profile is active)
server.port=8080
spring.jpa.open-in-view=false

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true